/**
 * @file boot_config.h
 * @brief ESP32-C6 Flash Partition Layout & Boot Configuration
 *
 * Defines the memory partitioning of the 4MB SPI flash for the ESP32-C6
 * target. In production, this file is auto-generated by the Manifest
 * Compiler (`toob-manifest compile`) from:
 *
 *   1. manifests/generic_esp32c6.toml     — Device identity & feature flags
 *   2. aggregated_scan.json               — Fuzzer-verified sector geometry
 *   3. blueprint.json                     — Boot vectors & memory regions
 *
 * FLASH GEOMETRY (from aggregated_scan.json run_33):
 *   - Total: 4MB (0x400000)
 *   - Sectors: Uniform 4KB (verified: 960 sectors from 0x40000..0x3FFFFF)
 *   - First 256KB (0x00000-0x3FFFF): BootROM reserved ("skipped")
 *   - Write alignment: 4 bytes
 *   - Erased byte: 0xFF
 *
 * PARTITION MAP (concept_fusion.md Section 3 + Delta Anti-Brick):
 *
 *   ┌──────────────────────────────────────────────────┐ 0x000000
 *   │  BootROM Reserved (256 KB)                       │
 *   │  aggregated_scan: "skipped" — DO NOT TOUCH       │
 *   ├──────────────────────────────────────────────────┤ 0x040000
 *   │  Stage 0 (16 KB, immutable)                      │
 *   ├──────────────────────────────────────────────────┤ 0x044000
 *   │  Stage 1 Bank A (28 KB)                          │
 *   ├──────────────────────────────────────────────────┤ 0x04B000
 *   │  Stage 1 Bank B (28 KB)                          │
 *   ├──────────────────────────────────────────────────┤ 0x052000
 *   │  Reserved / Alignment Pad (56 KB to 64KB align)  │
 *   ├──────────────────────────────────────────────────┤ 0x060000
 *   │  App Slot (384 KB)                               │
 *   │  (Active firmware, XIP from 0x42060000)          │
 *   ├──────────────────────────────────────────────────┤ 0x0C0000
 *   │  Staging Slot (384 KB)                           │
 *   │  (New firmware / delta patch landing zone)       │
 *   ├──────────────────────────────────────────────────┤ 0x120000
 *   │  WAL Journal (16 KB = 4 sectors)                 │
 *   │  (TMR striped across sectors for anti-bit-rot)   │
 *   ├──────────────────────────────────────────────────┤ 0x124000
 *   │  Recovery OS (128 KB)                            │
 *   ├──────────────────────────────────────────────────┤ 0x144000
 *   │  LP-Core / NetCore Slot (64 KB)                  │
 *   ├──────────────────────────────────────────────────┤ 0x154000
 *   │  Scratch / Delta Safe Buffer (384 KB)            │
 *   │  (Must fit CHIP_APP_SLOT_SIZE for delta output!) │
 *   ├──────────────────────────────────────────────────┤ 0x1B4000
 *   │  NVS / User Data (304 KB)                        │
 *   └──────────────────────────────────────────────────┘ 0x200000
 *                                                       (2MB usable)
 *
 * DESIGN RATIONALE:
 * - App Slot starts at 0x060000 (384KB offset) to satisfy the 64KB
 *   alignment requirement (CHIP_APP_ALIGNMENT_BYTES) verified by blueprint.json.
 * - App and Staging are equal size to enable full-image OTA without delta.
 * - Scratch/Delta buffer MUST be >= CHIP_APP_SLOT_SIZE because boot_state.c
 *   uses it as delta output target (boot_delta_apply writes a full image here).
 * - WAL is placed BEFORE scratch to protect it from partial delta writes.
 * - WAL uses 4 sectors for the sliding-window ring (concept_fusion.md Sec 2).
 * - BootROM reserved region (0x00000-0x3FFFF) was identified by the fuzzer
 *   as "skipped" — the BootROM expects its header data there.
 * - Flash is 4MB but we conservatively use 2MB to leave headroom for
 *   larger NVS or future expansion.
 */

#ifndef BOOT_CONFIG_H
#define BOOT_CONFIG_H

#include <stdint.h>

/* ========================================================================
 * PARTITION ADDRESSES (Physical flash offsets)
 *
 * All addresses are relative to flash base 0x0.
 * For XIP access, add CHIP_FLASH_XIP_BASE (0x42000000).
 * ======================================================================== */

/* BootROM reserved: 0x000000 - 0x03FFFF (256KB, "skipped" in aggregated_scan) */
#define CHIP_BOOTROM_RESERVED_END    0x00040000U

/* Stage 0: Immutable first-stage bootloader */
#define CHIP_STAGE0_ABS_ADDR         0x00040000U
#define CHIP_STAGE0_SIZE             0x00004000U  /* 16 KB */

/* Stage 1: Updateable bootloader engine (Dual-Bank for safe self-update) */
#define CHIP_STAGE1A_ABS_ADDR        0x00044000U
#define CHIP_STAGE1A_SIZE            0x00007000U  /* 28 KB */
#define CHIP_STAGE1B_ABS_ADDR        0x0004B000U
#define CHIP_STAGE1B_SIZE            0x00007000U  /* 28 KB */

/* App Slot: Active firmware (64KB-aligned for XIP) */
#define CHIP_APP_SLOT_ABS_ADDR       0x00060000U
#define CHIP_APP_SLOT_SIZE           0x00060000U  /* 384 KB */

/* Staging Slot: OTA landing zone (same size as App for full-image support) */
#define CHIP_STAGING_SLOT_ABS_ADDR   0x000C0000U
#define CHIP_STAGING_SLOT_SIZE       0x00060000U  /* 384 KB */
#define CHIP_STAGING_SLOT_ID         2U

/* WAL Journal: 4 rotating sectors for sliding-window ring.
 * Placed BEFORE scratch to ensure delta writes cannot corrupt it. */
#define TOOB_WAL_BASE_ADDR           0x00120000U
#define TOOB_WAL_SECTORS             4U
#define CHIP_WAL_SECTORS             TOOB_WAL_SECTORS
#define TOOB_WAL_SIZE                (TOOB_WAL_SECTORS * 0x1000U) /* 16 KB */

/* Per-sector address and size arrays for stage0 (stage0_boot_pointer.c)
 * and libtoob (toob_wal_naive.c). Supports asymmetric geometries on
 * chips with non-uniform sectors; ESP32-C6 is uniform 4KB. */
#define TOOB_WAL_SECTOR_ADDRS { \
    0x00120000U, \
    0x00121000U, \
    0x00122000U, \
    0x00123000U  \
}
#define TOOB_WAL_SECTOR_SIZES { \
    4096U, \
    4096U, \
    4096U, \
    4096U  \
}

/* Recovery OS */
#define CHIP_RECOVERY_OS_ABS_ADDR    0x00124000U
#define CHIP_RECOVERY_OS_SIZE        0x00020000U  /* 128 KB */

/* LP-Core / NetCore Slot (blueprint.json: coprocessors[0] = lp_core) */
#define CHIP_NETCORE_SLOT_ABS_ADDR   0x00144000U
#define CHIP_NETCORE_SLOT_SIZE       0x00010000U  /* 64 KB */

/*
 * Scratch / Delta Safe Buffer.
 * CRITICAL: Must be >= CHIP_APP_SLOT_SIZE because boot_state.c calls
 * boot_delta_apply() with this region as the delta output target.
 * Also used by boot_swap_apply() for atomic sector-level backup. */
#define CHIP_SCRATCH_SLOT_ABS_ADDR   0x00154000U
#define CHIP_SCRATCH_SLOT_SIZE       CHIP_APP_SLOT_SIZE  /* 384 KB (matches App) */

/* NVS / User Data: Remaining flash */
#define CHIP_NVS_ABS_ADDR            0x001B4000U

/* Flash base for bounds checking */
#define CHIP_FLASH_BASE_ADDR         0x00000000U

/* ========================================================================
 * CRYPTO ARENA (Monocypher software — no HW SHA in ESP32-C6 BootROM)
 *
 * Size derived from blueprint.json crypto_capabilities:
 *   hw_sha256=true but no ROM API → software fallback.
 *   Monocypher Blake2b context: ~200 bytes.
 *   Ed25519 verify workspace: ~1600 bytes.
 *   Total with alignment margin: 2048 bytes.
 * ======================================================================== */
#define BOOT_CRYPTO_ARENA_SIZE       2048U

/* ========================================================================
 * BOOT BEHAVIOR CONFIGURATION
 * ======================================================================== */

/* Max retries before entering recovery (concept_fusion.md Sec 1.A) */
#define BOOT_CONFIG_MAX_RETRIES           3U
#define BOOT_CONFIG_MAX_RECOVERY_RETRIES  3U

/* Brownout exponential backoff base (concept_fusion.md Sec 2) */
#define BOOT_CONFIG_BACKOFF_BASE_S        3600U  /* 1 hour */

/* Edge/unattended mode — no user interaction expected */
#define BOOT_CONFIG_EDGE_UNATTENDED_MODE  false

/* ========================================================================
 * STATIC ASSERTIONS (Compile-time layout sanity checks)
 * ======================================================================== */

/* Verify no partition overlap (chain: App → Staging → WAL → Recovery → NetCore → Scratch → NVS) */
_Static_assert(CHIP_APP_SLOT_ABS_ADDR + CHIP_APP_SLOT_SIZE <= CHIP_STAGING_SLOT_ABS_ADDR,
    "App Slot overlaps Staging Slot!");
_Static_assert(CHIP_STAGING_SLOT_ABS_ADDR + CHIP_STAGING_SLOT_SIZE <= TOOB_WAL_BASE_ADDR,
    "Staging Slot overlaps WAL!");
_Static_assert(TOOB_WAL_BASE_ADDR + TOOB_WAL_SIZE <= CHIP_RECOVERY_OS_ABS_ADDR,
    "WAL overlaps Recovery OS!");
_Static_assert(CHIP_RECOVERY_OS_ABS_ADDR + CHIP_RECOVERY_OS_SIZE <= CHIP_NETCORE_SLOT_ABS_ADDR,
    "Recovery OS overlaps NetCore Slot!");
_Static_assert(CHIP_NETCORE_SLOT_ABS_ADDR + CHIP_NETCORE_SLOT_SIZE <= CHIP_SCRATCH_SLOT_ABS_ADDR,
    "NetCore overlaps Scratch!");
_Static_assert(CHIP_SCRATCH_SLOT_ABS_ADDR + CHIP_SCRATCH_SLOT_SIZE <= 0x00200000U,
    "Scratch exceeds 2MB usable boundary!");

/* Scratch MUST fit a full app image for delta output (boot_state.c:324) */
_Static_assert(CHIP_SCRATCH_SLOT_SIZE >= CHIP_APP_SLOT_SIZE,
    "Scratch buffer too small for delta output!");

/* Verify App Slot alignment (blueprint.json: app_alignment_bytes = 65536) */
_Static_assert((CHIP_APP_SLOT_ABS_ADDR % 65536U) == 0U,
    "App Slot must be 64KB aligned for XIP!");

/* Verify Staging Slot is sector-aligned */
_Static_assert((CHIP_STAGING_SLOT_ABS_ADDR % 4096U) == 0U,
    "Staging Slot must be sector-aligned!");

/* Verify WAL base is sector-aligned */
_Static_assert((TOOB_WAL_BASE_ADDR % 4096U) == 0U,
    "WAL base must be sector-aligned!");

/* ========================================================================
 * LINKER-ACCESSIBLE EXTERN (crypto_arena is placed by the linker)
 * ======================================================================== */
extern uint8_t crypto_arena[BOOT_CRYPTO_ARENA_SIZE];

#endif /* BOOT_CONFIG_H */
