/**
 * @file chip_config.h
 * @brief ESP32-C6 Hardware Constants (Fuzzer-Verified + SVD Cross-Referenced)
 *
 * This file provides the complete hardware wiring for the ESP32-C6 target.
 * In production, it is auto-generated by the Manifest Compiler from the
 * blueprint.json. For initial bring-up, values are hardcoded from:
 *
 * VERIFICATION SOURCES:
 * 1. blueprints/quirks/esp32-c6.json (Toobfuzzer hardware fuzzing)
 * 2. aggregated_scan.json (4MB flash, uniform 4KB sectors)
 * 3. esp32c6.rom.ld (Official Espressif ROM linker symbols)
 * 4. Device.swift / SVD registers (SVD-generated peripheral base addresses)
 * 5. ESP-IDF lpwdt_ll.h (WDT unlock key 0x50D83AA1)
 */

#ifndef CHIP_CONFIG_H
#define CHIP_CONFIG_H

#include <stdint.h>

/* ========================================================================
 * FLASH GEOMETRY (aggregated_scan.json: 4MB uniform 4KB sectors)
 * ======================================================================== */
#define CHIP_FLASH_TOTAL_SIZE       (4U * 1024U * 1024U)   /* 0x400000 */
#define CHIP_FLASH_MAX_SECTOR_SIZE  4096U
#define CHIP_FLASH_WRITE_ALIGNMENT  4U
#define CHIP_APP_ALIGNMENT_BYTES    65536U
#define CHIP_FLASH_ERASED_BYTE      0xFFU

/**
 * Flash XIP mapping base address.
 * On ESP32-C6, flash is memory-mapped starting at 0x42000000.
 * Physical flash offset 0x0 → virtual address 0x42000000.
 */
#define CHIP_FLASH_XIP_BASE         0x42000000U

/* ========================================================================
 * ROM FUNCTION POINTERS (esp32c6.rom.ld + quirks/esp32-c6.json)
 *
 * Cross-verified against two independent sources:
 *   Fuzzer quirks:  erase=0x40000144, write=0x4000014c, unlock=0x40000154
 *   esp32c6.rom.ld: erase=0x40000144, write=0x4000014c, unlock=0x40000154
 * ======================================================================== */
#define ROM_PTR_FLASH_ERASE   ((int (*)(uint32_t))0x40000144)
#define ROM_PTR_FLASH_WRITE   ((int (*)(uint32_t, const void*, uint32_t))0x4000014c)
#define ROM_PTR_FLASH_READ    ((int (*)(uint32_t, void*, uint32_t))0x40000150)
#define ROM_PTR_FLASH_UNLOCK  ((int (*)(void))0x40000154)

/* ========================================================================
 * WATCHDOG REGISTERS (quirks/esp32-c6.json + lpwdt_ll.h)
 *
 * Key: 0x50D83AA1 verified against ESP-IDF source and toobfuzzer run.
 * Base addresses verified against SVD Device.swift:
 *   TIMG0=0x60008000, LP_WDT=0x600B1C00
 * ======================================================================== */
#define REG_TIMG0_WDT_CONFIG0      0x60008048U
#define REG_TIMG0_WDT_FEED         0x60008060U
#define REG_TIMG0_WDT_WPROTECT     0x60008064U

#define REG_TIMG1_WDT_CONFIG0      0x60009048U
#define REG_TIMG1_WDT_WPROTECT     0x60009064U

#define VAL_WDT_UNLOCK             0x50D83AA1U

#define REG_LP_WDT_CONFIG0         0x600B1C00U
#define REG_LP_WDT_WPROTECT        0x600B1C18U
#define REG_LP_WDT_SWD_CONFIG      0x600B1C1CU
#define REG_LP_WDT_SWD_WPROTECT    0x600B1C20U
#define REG_LP_WDT_FEED            0x600B1C14U

/* SWD exists on C3/C6/H2. ESP32 Classic and S2/S3 do NOT have SWD. */
#define CHIP_HAS_SWD               1

/* ========================================================================
 * CONFIRM STORAGE (LP_RAM — fuzzer RAM boundary scan)
 *
 * LP_RAM at 0x50000000 survives all reset types except full power loss.
 * Verified via aggregated_scan.json ram_fuzzed_boundaries: 0x50002000.
 * ======================================================================== */
#define ADDR_CONFIRM_RTC_RAM  ((volatile uint64_t *)0x50000000U)

/* ========================================================================
 * RESET REASON (PMU register)
 *
 * PMU base: 0x600B0000 (SVD Device.swift).
 * Reset cause at offset 0x0410 (ESP32-C6 TRM Section 7.3.1).
 * ======================================================================== */
#define REG_RESET_CAUSE            0x600B0410U
#define REG_RESET_CAUSE_MASK       0x1FU

/* Reset cause codes (ESP32-C6 TRM Table 7-2). Other chips have different values. */
#define CHIP_RST_POWERON           1U
#define CHIP_RST_SW_SYS            3U
#define CHIP_RST_DEEPSLEEP         5U
#define CHIP_RST_TG0WDT            7U
#define CHIP_RST_TG1WDT            8U
#define CHIP_RST_RTCWDT_SYS        9U
#define CHIP_RST_TG0WDT_CPU       11U
#define CHIP_RST_SW_CPU            12U
#define CHIP_RST_RTCWDT_CPU       13U
#define CHIP_RST_BROWNOUT          15U
#define CHIP_RST_RTCWDT_RTC       16U
#define CHIP_RST_SWD               18U

/* ========================================================================
 * TIMING / SYSTIMER (SVD Device.swift: SYSTIMER base = 0x6000A000)
 *
 * SYSTIMER runs at fixed 16 MHz on ESP32-C6, independent of CPU clock.
 * ======================================================================== */
#define CHIP_SYSTIMER_BASE         0x6000A000U
#define CHIP_CPU_FREQ_HZ           160000000U

/* ========================================================================
 * UART0 (SVD Device.swift: UART0 base = 0x60000000)
 * ======================================================================== */
#define CHIP_UART0_BASE            0x60000000U
#define CHIP_UART0_TX_PIN          16U
#define CHIP_UART0_RX_PIN          17U
#define CHIP_UART_SCLK_FREQ        40000000U  /* XTAL 40 MHz. ESP32 Classic: APB 80 MHz */
#define CHIP_UART_TX_FIFO_SIZE     128U

/* ========================================================================
 * WDT TIMEOUT (Manifest Compiler: longest_operation + 2x margin)
 *
 * Longest single operation: sector erase ~45ms.
 * With 2x margin: 90ms. Rounded up to next hardware step: 5000ms
 * for comfortable boot-time coverage.
 * ======================================================================== */
#define BOOT_WDT_TIMEOUT_MS        5000U

/* ========================================================================
 * PCR (Peripheral Clock Register) for enabling UART/SYSTIMER clocks
 * PCR base: 0x60096000 (SVD Device.swift)
 * ======================================================================== */
#define CHIP_PCR_BASE              0x60096000U

#endif /* CHIP_CONFIG_H */
