/**
 * @file chip_config.h
 * @brief ESP32-C6 Hardware Constants (Fuzzer-Verified + SVD Cross-Referenced)
 *
 * This file provides the complete hardware wiring for the ESP32-C6 target.
 * In production, it is auto-generated by the Manifest Compiler from the
 * blueprint.json. For initial bring-up, values are hardcoded from:
 *
 * VERIFICATION SOURCES:
 * 1. blueprints/quirks/esp32-c6.json (Toobfuzzer hardware fuzzing)
 * 2. aggregated_scan.json (4MB flash, uniform 4KB sectors)
 * 3. esp32c6.rom.ld (Official Espressif ROM linker symbols)
 * 4. Device.swift / SVD registers (SVD-generated peripheral base addresses)
 * 5. ESP-IDF lpwdt_ll.h (WDT unlock key 0x50D83AA1)
 */

#ifndef CHIP_CONFIG_H
#define CHIP_CONFIG_H

#include <stdint.h>
#include "generated_boot_config.h"

/* ========================================================================
 * APP ALIGNMENT & DEFAULTS
 * ======================================================================== */
#define CHIP_APP_ALIGNMENT_BYTES    65536U
#define CHIP_FLASH_ERASED_BYTE      0xFFU

/* ========================================================================
 * WDT TIMEOUT (Manifest Compiler: longest_operation + 2x margin)
 *
 * Longest single operation: sector erase ~45ms.
 * With 2x margin: 90ms. Rounded up to next hardware step: 5000ms
 * for comfortable boot-time coverage.
 * ======================================================================== */
#ifndef BOOT_WDT_TIMEOUT_MS
#define BOOT_WDT_TIMEOUT_MS        5000U
#endif

#endif /* CHIP_CONFIG_H */
